version: '3.9'

services:
  app:
    container_name: app
    build:
      context: .
      args:
        - POETRY_DEV=true
    env_file:
      - env-local
    volumes:
      - ./app:/app
    ports:
      - 7777:80
    # depends_on:
    #   - db
    command: >
      bash -c "python manage.py runserver 0.0.0.0:80"

#   db:
#     container_name: db
#     image: postgres:13.7
#     env_file:
#       - env-local
#     volumes:
#       - db-data:/var/lib/postgresql/data:delegated

# volumes:
#   db-data: