---
name: Checks

on: push

jobs:
  test_and_lint:
    name: Test and Lint
    runs-on: ubuntu-22.04

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Test
        run: |
          docker-compose run --rm app bash -c "python manage.py wait_for_db && python manage.py test"
      
      - name: Lint
        run: |
          docker-compose run --rm app bash -c "flake8"